#Copyright IBM Corp. All Rights Reserved.
#SPDX-License-Identifier: Apache-2.0

[[constraint]]
  version = "0.23.0"
  name = "github.com/hyperledger/burrow"

[[constraint]]
  version = "=1.3.0"
  name = "github.com/hyperledger/fabric"

#[[constraint]]
#  branch = "master"
#  name = "github.com/onsi/gomega"

[[constraint]]
  branch = "master"
  name = "github.com/hyperledger/fabric-sdk-go"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.3.5"

#Constraints from Burrow
[[override]]
  version = "=0.8.1"
  name = "github.com/tendermint/tmlibs"

[[override]]
  version = "0.5.0"
  name = "github.com/tendermint/go-crypto"

#Constraints from Fabric
[[override]]
  version = "1.13.0"
  name = "google.golang.org/grpc"

[[override]]
  revision = "292b43bbf7cb8d35ddf40f8d5100ef3837cced3f"
  name = "golang.org/x/net"

[[constraint]]
  revision = "a3b6351eb1ff8e1bfa30b2f55d7e282186ed8fee"
  name = "github.com/onsi/ginkgo"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.2"

#[[override]]
#  revision = "57142e89befe90977da6dce7762f9fcc70f28da1"
#  name = "github.com/docker/docker"

[[override]]
  name = "github.com/docker/docker"
  branch = "master"

[[override]]
  version = "0.8.0"
  name = "github.com/pkg/errors"

[[override]]
  revision = "df60624c1e9b9d2973e889c7a1cff73155da81c4"
  name = "google.golang.org/genproto"

[[override]]
  version = "1.1.0"
  name = "github.com/golang/protobuf"

[[override]]
  revision = "6b78f7a22d950103fb2669aabb969f56d42d283b"
  name = "github.com/hyperledger/fabric-amcl"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.0"

#Constraints from fabric-sdk-go
[[override]]
  revision = "aafc9e6bc7b7bb53ddaa75a5ef49a17d6e654be5"
  name = "github.com/spf13/viper"

[[override]]
  revision = "7600349dcfe1abd18d72d3a1770870d9800a7801"
  name = "github.com/prometheus/common"

[[override]]
  revision = "ae68e2d4c00fed4943b5f6698d504a5fe083da8a"
  name = "github.com/prometheus/procfs"

#Constraints from go-dockerclient
[[override]]
  name = "github.com/docker/libnetwork"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
      name = "github.com/onsi/ginkgo"
      unused-packages = false
      non-go = true

#  [[prune.project]]
#      name = "github.com/onsi/gomega"
#      unused-packages = false
#      non-go = true
